# @baseUrl = http://localhost:3000/menu
@baseUrl = https://menu-rest-api.onrender.com/menu

### SEND REQUEST
GET {{baseUrl}}

### SEND REQUEST WITH FILTER
GET {{baseUrl}}/?name=Pizza

### SEND REQUEST TO GET A SPECIFIC DISH
GET {{baseUrl}}/1

### POST A DISH
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Pizzaaa",
    "price": 9.8,
    "description": "Pizza con pepperoni",
    "rate": 9.9
}
### PATCH A DISH
PATCH {{baseUrl}}/5
Content-Type: application/json

{
    "name": "test updated",
    "price": 15,
    "description": "testeo updated",
    "rate": 4.5
}
### DELETE A DISH
DELETE {{baseUrl}}/6

###
