# @baseUrl = http://localhost:3000
@baseUrl = https://menu-rest-api.onrender.com

### SEND REQUEST
GET {{baseUrl}}/menu

### SEND REQUEST WITH FILTER
GET {{baseUrl}}/menu?name=pizza

### POST A DISH
POST {{baseUrl}}/menu
Content-Type: application/json

{
    "name": "test",
    "price": 10,
    "description": "testeo",
    "rate": 5
}
### PATCH A DISH
PATCH {{baseUrl}}/menu/1001
Content-Type: application/json

{
    "name": "test updated",
    "price": 15,
    "description": "testeo updated",
    "rate": 4.5
}
### DELETE A DISH
DELETE {{baseUrl}}/menu/1001

###
