# @baseUrl = http://localhost:3000
@baseUrl = https://menu-rest-api.onrender.com/menu

### SEND REQUEST
GET {{baseUrl}}

### SEND REQUEST WITH FILTER
GET {{baseUrl}}/?name=pizza

### SEND REQUEST TO GET A SPECIFIC DISH
GET {{baseUrl}}/1001

### POST A DISH
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "test",
    "price": 10,
    "description": "testeo",
    "rate": 5
}
### PATCH A DISH
PATCH {{baseUrl}}/1001
Content-Type: application/json

{
    "name": "test updated",
    "price": 15,
    "description": "testeo updated",
    "rate": 4.5
}
### DELETE A DISH
DELETE {{baseUrl}}/1001

###
